server:
  port: 8080

spring:
  application:
    name: hackaton
  datasource:
    url: jdbc:mysql://localhost:3306/hackaton
    username: user
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  mail:
    host: live.smtp.mailtrap.io
    port: 2525
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true