server:
  port: 8080

spring:
  application:
    name: hackaton
  datasource:
    url: jdbc:mysql://localhost:3306/hackaton
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update